
####################################
######     Global start     ######
####################################
name                : 'Trust Alliance'
title               : 'Trust Alliance - Technology for All'
email               : hello@trustalliance.org.au
address             : 'c/- Australian Red Cross'
phone               : 038123 4567
tagline             : 'Lead the emergence of a useful and ethical identity ecosystem' 
description: >- # this means to ignore newlines until "baseurl:"
  The Trust Alliance guiding purpose is to lead the emergence of a useful and ethical identity ecosystem.
baseurl             : "" # the subpath of your site, e.g. /blog
url                 : "http://127.0.0.1:4000/" #  7277783  the base hostname & protocol for your site, e.g. http://example.com
twitter_username    : trustalliance
github_username     : trustalliance

paginate: 12
paginate_path: "/blog/page:num/"



# Build settings
markdown            : kramdown

# all plugin
plugins:
  - jekyll-feed

# google_analytics
google_analytics: ''

# disqus comment
disqus:
  shortname: ''


####################################
######     Hero start     ######
####################################
# product_background_image          sass
# product_fixed_image               saas_video             
# product                           sass_background_image
# product_slider                    sass_fixed_image
# product_video                     sass_slider       

hero: 'sass'

# sass [ only one image ]
hero_sass_name: 'Create a Useful and Ethical Digital Identity Ecosystem'
hero_sass_text: 'The Trust Alliance is a coalition of individuals and organisations working together to further the adoption of open identity solutions and values.'
hero_sass_image: 'img/hero/connected_world.png'
hero_sass_btn_one_link: '#'
hero_sass_btn_one_text:  'Join Us'
hero_sass_btn_two_link: '/blog'
hero_sass_btn_two_text: ' Recent Activities '

# saas_video [ video type mp4 ]
hero_saas_video_name: 'We Made our <br> Software 100% Errorless' 
hero_saas_video_text: 'The first is a non technical method which requires the use of adware removal software.  Download free adware and spyware removal software and use advanced tools to help prevent  getting infected.'
hero_saas_video_image: 'img/mockup.png'
hero_saas_video_video: 'vdo/sass-bv.mp4'
hero_saas_video_btn_one_link: '#'
hero_saas_video_btn_one_text:  'Browse free demo'

# sass_background_image
hero_sass_background_image_name: 'We Made our <br> Software 100% Errorless' 
hero_sass_background_image_text: 'The first is a non technical method which requires the use of adware removal software.  Download free adware and spyware removal software and use advanced tools to help prevent  getting infected.'
hero_sass_background_image_image: 'img/mockup.png'
hero_sass_background_image_btn_one_link: '#'
hero_sass_background_image_btn_one_text:  'Browse free demo'

# sass_fixed_image
hero_saas_fixed_image_name: 'We Made our <br> Software 100% Errorless' 
hero_saas_fixed_image_text: 'The first is a non technical method which requires the use of adware removal software.  Download free adware and spyware removal software and use advanced tools to help prevent  getting infected.'
hero_saas_fixed_image_image: 'img/mockup.png'
hero_saas_fixed_image_btn_one_link: '#'
hero_saas_fixed_image_btn_one_text:  'Browse free demo'

# sass_slider
hero_sass_slider_name: 'We Made our <br> Software 100% Errorless' 
hero_sass_slider_image: 'img/mockup.png'
hero_sass_slider_btn_one_link: '#'
hero_sass_slider_btn_one_text:  'Browse free demo'
hero_sass_slider: 
  - image: 'img/carusel/s1.jpg'
  - image: 'img/carusel/s2.jpg'
  - image: 'img/carusel/s3.jpg'

# product [ only one image ]
hero_product_name: 'The most Creative <br> Theme ever for Business'
hero_product_text: 'The first is a non technical method which requires the use of adware removal software. Download  free adware and spyware removal software and use advanced tools to help prevent getting infected.'
hero_product_image: 'img/hero/hero-img2.png'
hero_product_btn_one_link: '#'
hero_product_btn_one_text:  'Browse free demo'

# product_video [ video type mp4 ]
hero_product_video_name: 'The most Creative <br> Theame ever in Business' 
hero_product_video_text: 'The first is a non technical method which requires the use of adware removal software. ownload free adware and spyware removal'
hero_product_video_image: 'img/iPhoneX.png'
hero_product_video_video: 'vdo/app-bv.mp4'
hero_product_video_btn_one_link: '#'
hero_product_video_btn_one_text:  'Browse free demo'

# product_background_image
hero_product_background_image_name: 'The most Creative <br> Theame ever in Business' 
hero_product_background_image_text: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools to help prevent getting infected.'
hero_product_background_image_image: 'img/iPhoneX.png'
hero_product_background_image_btn_one_link: '#'
hero_product_background_image_btn_one_text:  'Browse free demo'

# product_fixed_image
hero_product_fixed_image_name: 'The most Creative <br> Theame ever in Business' 
hero_product_fixed_image_text: 'The first is a non technical method which requires the use of adware removal software.  Download free adware and spyware removal software and use advanced tools to help prevent  getting infected.'
hero_product_fixed_image_image: 'img/iPhoneX.png'
hero_product_fixed_image_btn_one_link: '#'
hero_product_fixed_image_btn_one_text:  'Browse free demo'

# product_slider
hero_product_slider_name: 'The most Creative <br> Theame ever in Business' 
hero_product_slider_text: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools to help prevent getting infected.'
hero_product_slider_image: 'img/iPhoneX.png'
hero_product_slider_btn_one_link: '#'
hero_product_slider_btn_one_text:  'Browse free demo'
hero_product_slider: 
  - image: 'img/carusel/a1.jpg'
  - image: 'img/carusel/a2.jpg'
  - image: 'img/carusel/a3.jpg'

# hero-section-blog

hero_blog_slider:
  - image: 'img/hero/hero-blog.jpg'
    author: 'Sir Alex James'
    title: 'The Idea Of God Is <br /> Not Henceforth Relevant'
    category: 'Technical'

  - image: 'img/hero/hero-blog.jpg'
    author: 'Sir Alex James'
    title: 'The Idea Of God Is <br /> Not Henceforth Relevant'
    category: 'Art &amp; Fantacy'



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

####################################
######      Global end      ######
####################################





####################################
######  feature Section   ######
####################################

feature_image_one: 'img/feature/i1.png'
feature_title_one: 'Research & Impact'
feature_description_one: 'Some days a motivational quote can provide a quick pick-me-up for employees and even  management.'

feature_image_two: 'img/feature/i3.png'
feature_title_two: 'Pilots & Programs'
feature_description_two: 'Some days a motivational quote can provide a quick pick-me-up for employees and even management.'

feature_image_three: 'img/feature/i4.png'
feature_title_three: 'Technical Standards & Governance'
feature_description_three: 'Some days a motivational quote can provide a quick pick-me-up for employees and even management.'


####################################
######  marketing Section   ######
####################################
marketing_title: 'Build Your Brand  Automate Your Marketing'
marketing_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools to help prevent getting infected. Spyware scan review is a free service for anyone interested in downloading spyware/adware removal software. Our adware remover is the most trusted.'
marketing_image_one: '/img/marketing/d1.png'
marketing_image_two: '/img/marketing/d2.png'
marketing_btn_text: 'Browse free demo'
marketing_btn_link: '#'


####################################
######  Statistics Section    ######
####################################
statistics_title: 'How You or Your Organisation can Get Involved.'
statistics_description: 'The Trust Alliance is organised around four primary working groups. Working groups are member lead, and welcoming of new values aligned individuals or organisations who would like to contribute.'
statistics_image: 'img/title-icon.png'

# main big image
statistics_start_image: 'img/stat/stat-img.png'

# 4 section image
statistics_item_one_image: 'img/stat/s1.png'
statistics_item_one_title: 'Research & Impact'
statistics_item_one_link: '#'
statistics_item_one_description: 'Develop a research agenda that addresses the issues and opportnunities with trusted digital credentials as well as measure and evaluate the impact of the initiative including the development of an Impact Model.'

statistics_item_two_image: 'img/stat/s2.png'
statistics_item_two_title: 'Pilots & Programs'
statistics_item_two_link: '#'
statistics_item_two_description: 'Identification, prioritisation and development of pilots and projects that support the use of trusted credentials and deliver insights and learnings back to the Trust Alliance.'

statistics_item_three_image: 'img/stat/s2.png'
statistics_item_three_title: 'Steering Committee'
statistics_item_three_link: '#'
statistics_item_three_description: 'Chair / CEO of the Trust Alliance, along with core team that guide the overall direction of the Trust Alliance as well as advocate for and build partnerships to progress the adoption of trusted digital credentials.'

statistics_item_four_image: 'img/stat/s4.png'
statistics_item_four_title: 'Technical Standards & Governance'
statistics_item_four_link: '#'
statistics_item_four_description: 'Development of the model for technical governenace of a registry of trusted organisations to enable credentials to be shared.'

####################################
######    cta Section      ######
####################################
cta_title: 'Want to support in other ways? Keep in touch...'
cta_btn_link_one: '#'
cta_btn_text_one: 'Signup for Newsletter'
cta_btn_link_two: '#'
cta_btn_text_two: 'Contact Us'

####################################
######    Social Section      ######
####################################
social_title: 'Manage Social Network with Our Managing Toolkit'
social_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools to help prevent getting infected. Spyware scan review is a free service for anyone interested in downloading spyware/adware removal software. Our adware remover is the most trusted.'
social_image: 'img/social-img.png'
social_button_text: 'Browse free demo'
social_button_link: '#'


#####################################
########## Pricing Tables ###########
#####################################
pricing-table-title: 'Trust Alliance Membership Fees'
pricing-table-description: "Trust Alliance membership fees are reinvested into the organisation, contributing toward membership activities and support."

# Personal Plan
plan-starter-name: individuals
plan-starter-tagline: Individual membership
plan-starter-price: '<span>A$100</span>/yr'
plan-starter-offer-line-1-info:  Offer 1
plan-starter-offer-line-2-info:  Offer 2
plan-starter-offer-line-3-info:  Offer 3
plan-starter-url: '#'
plan-starter-btn_text: 'Apply Now'

# Team Plan
plan-standard-name: organisation
plan-standard-tagline: NFP, corporate, education, & government membership
plan-standard-price: '<span>A$1,000</span>/yr'
plan-standard-offer-line-1-info: Access to Trust Alliance members forum
plan-standard-offer-line-2-info: Participation in all activities & events
plan-standard-offer-line-3-info: Join or create working groups
plan-standard-url: '#'
plan-standard-btn_text: 'Apply Now'


# business Plan
plan-business-name: sponsor
plan-business-tagline: Trust Alliance sponsorship
plan-business-price: '<span>A$10,0000</span>/yr'
plan-business-offer-line-1-info: Everything in Organisation membership
plan-business-offer-line-2-info: Brand recognition on website and at events
plan-business-offer-line-3-info: Reserved space in Trust Alliance newsletter
plan-business-url: '#'
plan-business-btn_text: 'Contact Us'




#####################################
########## Pricing Tables ###########
#####################################

unique_feature_title: 'Features that make us Stand Out'
unique_feature_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'
unique_feature_image: 'img/title-icon.png' 

unique_feature_main_image_slider: 
  - image: 'img/carusel/c1.png'
  - image: 'img/carusel/c2.png'
  - image: 'img/carusel/c3.png'

unique_feature_section_one_title: 'Certifications'
unique_feature_section_one_description: 'We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day to day, also asks us to remain.'
unique_feature_section_one_image: http://127.0.0.1:4000/img/feature/f1.png
unique_feature_section_one_link: '#'

unique_feature_section_two_title: 'Page Builder'
unique_feature_section_two_description: 'Vera sought out counseling with me because her doctor advised her to discover the emotional causes of her chronic fatigue.'
unique_feature_section_two_image: http://127.0.0.1:4000/img/feature/f2.png
unique_feature_section_two_link: '#'


#####################################
#########  Brands Section ###########
#####################################
 
bands_slider:
  - image: 'img/brands/ARC.png'
    link: '#'
  - image: 'img/brands/boh.png'
    link: '#'
  - image: 'img/brands/oxfam.png'
    link: '#'
  - image: 'img/brands/redr.png'
    link: '#'
  - image: 'img/brands/RMIT.png'
    link: '#'
  - image: 'img/brands/Swinburne.png'
    link: '#'
  - image: 'img/brands/th.png'
    link: '#'
  - image: 'img/brands/b7.png'
    link: '#'
  - image: 'img/brands/b8.png'
    link: '#'
  - image: 'img/brands/b9.png'
    link: '#'
  - image: 'img/brands/b10.png'
    link: '#'




#####################################
########### Testimonials ############
#####################################

testimonials:

# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


# Client
- author: 'Travor James'
  avatar: '/img/review/user.png'
  position: 'Head of Marketing, Apple Inc.'
  quotes: 'Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'


#####################################
##########     Blog      ###########
#####################################
blog-title: 'Latest Posts from our Blog'
blog-description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'


#####################################
##########     Contact      ###########
#####################################
contact_title: 'Whenever You Need, Just Send a Message'
contact_description: 'The first is a non technical method which requires the use of adware removal software. Download free adware and spyware removal software and use advanced tools getting infected.'
contact_image: 'img/title-icon.png'
contact_email: 'support@demo.com'
contact_phone: '00 (440) 9865 562 9865'
contact_address: 'Los Angeles, United States'

#####################################
##########     footer      ###########
#####################################

footer_title: 'About Us'
footer_description: 'About 64% of all on-line teens say that do things online that they wouldn’t want their parents to know about. 11% of all adult internet user visit websites.'

footer_resources_link_heading: 'Resources'
footer_resources_link_one_text: 'Guides'
footer_resources_link_one_link: '#'
footer_resources_link_two_text: 'Research'
footer_resources_link_one_link: '#'
footer_resources_link_three_text: 'Experts'
footer_resources_link_one_link: '#'
footer_resources_link_four_text: 'Agencies'
footer_resources_link_one_link: '#'


footer_features_link_heading: 'Features'
footer_features_link_one_text: 'Guides'
footer_features_link_one_link: '#'
footer_features_link_two_text: 'Research'
footer_features_link_one_link: '#'
footer_features_link_three_text: 'Experts'
footer_features_link_one_link: '#'
footer_features_link_four_text: 'Agencies'
footer_features_link_one_link: '#'


footer_facebook_link: '#'
footer_twitter_link: '#'
footer_dribbble_link: '#'
footer_behance_link: '#'

mailchimp:
  user-id: 
  list-id: 


####################################
######        Copyright       ######
####################################
copyright_text: Copyright © 2019 All rights reserved to
company_url: '#'


# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#google map api key

map: 'AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA'